name: AI Code Review with Reviewpad

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Reviewpad AI Review
        uses: reviewpad/action@v3.x
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: .github/reviewpad.yml